# Generated by Django 2.2.3 on 2020-01-28 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200128_1409'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='errorcodes',
            options={'managed': True},
        ),
    ]
