# Generated by Django 2.2.3 on 2020-01-28 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200128_1412'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='errorcodes',
            options={'managed': False},
        ),
    ]
