# Generated by Django 2.2.3 on 2020-01-28 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200128_1430'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='records',
            options={'managed': True},
        ),
    ]
