# Generated by Django 2.2.3 on 2020-01-28 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200128_2239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='records',
            options={'managed': False},
        ),
    ]
