# Generated by Django 2.2.3 on 2020-01-29 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200128_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='re_errorid',
            field=models.ForeignKey(db_column='re_errorid', default='Error', on_delete=django.db.models.deletion.DO_NOTHING, to='main.ErrorCodes', verbose_name='Error Name'),
        ),
        migrations.AddField(
            model_name='records',
            name='re_image',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='records',
            name='re_labeledby',
            field=models.ForeignKey(db_column='re_labeledby', default='User', on_delete=django.db.models.deletion.DO_NOTHING, to='main.Users', verbose_name='Labeled By'),
        ),
        migrations.AddField(
            model_name='records',
            name='re_qualityid',
            field=models.ForeignKey(db_column='re_qualityid', default='Quality', on_delete=django.db.models.deletion.DO_NOTHING, to='main.QualityCodes', verbose_name='Quality Name'),
        ),
        migrations.AlterField(
            model_name='records',
            name='re_createdat',
            field=models.DateTimeField(verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='records',
            name='re_editedat',
            field=models.DateTimeField(verbose_name='Edited At'),
        ),
        migrations.AlterField(
            model_name='records',
            name='re_fabrictype',
            field=models.CharField(max_length=300, verbose_name='Fabric Type'),
        ),
        migrations.AlterField(
            model_name='records',
            name='re_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='records',
            name='re_path',
            field=models.CharField(max_length=300, verbose_name='Path'),
        ),
        migrations.CreateModel(
            name='RecordImageDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.Records')),
            ],
        ),
    ]
