# Generated by Django 2.2.3 on 2020-01-29 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200129_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='re_errorid',
            field=models.ForeignKey(db_column='re_errorid', default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='main.ErrorCodes', verbose_name='Error Name'),
        ),
        migrations.AlterField(
            model_name='records',
            name='re_labeledby',
            field=models.ForeignKey(db_column='re_labeledby', default=3, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Users', verbose_name='Labeled By'),
        ),
        migrations.AlterField(
            model_name='records',
            name='re_qualityid',
            field=models.ForeignKey(db_column='re_qualityid', default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='main.QualityCodes', verbose_name='Quality Name'),
        ),
    ]
