# Generated by Django 2.2.3 on 2020-01-29 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200129_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='re_errorid',
            field=models.ForeignKey(db_column='re_errorid', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='main.ErrorCodes', verbose_name='Error Name'),
        ),
    ]
