# Generated by Django 2.2.3 on 2020-01-29 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20200129_1148'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecordImageDetails',
        ),
    ]
