# Generated by Django 2.2.3 on 2020-01-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20200129_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='re_image',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Image'),
        ),
    ]
