# Generated by Django 2.2.3 on 2020-02-01 21:11

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20200129_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='re_createdat',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='records',
            name='re_errorid',
            field=models.ForeignKey(db_column='re_errorid', default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='main.ErrorCodes', verbose_name='Hata Adı'),
        ),
        migrations.AlterField(
            model_name='records',
            name='re_fabrictype',
            field=models.CharField(max_length=300, verbose_name='Kumaş Türü'),
        ),
        migrations.AlterField(
            model_name='records',
            name='re_image',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to=main.models.image_directory_path, verbose_name='Fotoğraf'),
        ),
        migrations.AlterField(
            model_name='records',
            name='re_qualityid',
            field=models.ForeignKey(db_column='re_qualityid', default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='main.QualityCodes', verbose_name='Kalite Adı'),
        ),
    ]
