# Generated by Django 2.2.3 on 2020-02-01 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20200202_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='re_errorid',
            field=models.ForeignKey(db_column='re_errorid', on_delete=django.db.models.deletion.DO_NOTHING, to='main.ErrorCodes', verbose_name='Hata Adı'),
        ),
        migrations.AlterField(
            model_name='records',
            name='re_labeledby',
            field=models.ForeignKey(db_column='re_labeledby', on_delete=django.db.models.deletion.DO_NOTHING, to='main.Users', verbose_name='Labeled By'),
        ),
        migrations.AlterField(
            model_name='records',
            name='re_qualityid',
            field=models.ForeignKey(db_column='re_qualityid', on_delete=django.db.models.deletion.DO_NOTHING, to='main.QualityCodes', verbose_name='Kalite Adı'),
        ),
    ]
