# Generated by Django 2.2.3 on 2020-02-03 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_records_re_searchdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='records',
            name='re_searchdate',
        ),
    ]
